img=imread('gray.tif');
[f1,f2]=freqspace(size(img),'meshgrid');
Hd=ones(size(img));
r=sqrt(f1.^2+f2.^2);
Hd(r>0.1)=0;
Y=fft2( double(img));
Y=fftshift(Y);
Ya=Y.*Hd;
Ya=ifftshift(Ya);
img1=ifft2(Ya);
Hd=ones(size(img));
Hd(r>0.2)=0;
Y=fft2(double(img));
Y=fftshift(Y);
Ya=Y.*Hd;
Ya=ifftshift(Ya);
img2=ifft2(Ya);
Hd=ones(size(img));
Hd(r>0.5)=0;
Y=fft2(double(img));
Y=fftshift(Y);
Ya=Y.*Hd;
Ya=ifftshift(Ya);
img5=ifft2(Ya);
subplot(221);imshow(uint8(img));
title('original image');
subplot(222);imshow(uint8(img1));
title('r=0.1');
subplot(223);imshow(uint8(img2));
title('r=0.2');
subplot(224);imshow(uint8(img5));
title('r=0.5');

