I=imread('gray.tif');
Len=30;
Theta=45;
PSF=fspecial('motion',Len,Theta);
BlurredA=imfilter(I,PSF,'circular','conv');
Wnr1=deconvwnr(BlurredA,PSF);
BlurredB=imfilter(I,PSF,'circ','conv');
INITPSF=ones(size(PSF));
[K,DePSF]=deconvblind(BlurredB,INITPSF,30);
BlurredB=imfilter(I,PSF,'conv');
V=0.02;
Blurred_I_Noisy=imnoise(BlurredB,'gaussian',0,V);
NP=V*prod(size(I));
J=deconvreg(Blurred_I_Noisy,PSF,NP);
BlurredC=imfilter(I,PSF,'symmetric','conv');
V=0.002;
BlurredNoisy=imnoise(BlurredC,'gaussian',0,V);
Luc=deconvlucy(BlurredNoisy,PSF,5);
subplot(231);imshow(I);
title('original image');
subplot(232);imshow(BlurredA);
title('motion blurred image');
subplot(233);imshow(Wnr1);
title('wenier');
subplot(234);imshow(J);
title('Least Square');
subplot(235);imshow(Luc);
title('Lucy');
subplot(236);imshow(K);
title('blind');